
config {
  type: "table",
  tags: ["link"],
  schema: "Row_Vault",
  partitionBy: "load_dts",
  clusterBy: ["PaymentID_bk", "BookingID_bk"]
}
 
SELECT
  TO_HEX(SHA256(CAST(CONCAT(l.PaymentID, l.BookingID) AS STRING))) AS PaymentID_BookingID_hk,
  CAST(l.PaymentID AS STRING) AS PaymentID_bk,
  CAST(l.BookingID AS STRING) AS BookingID_bk,
  CURRENT_DATE() AS load_dts,
  'SpiceJet_Booking_Details' AS record_source
FROM
  ${ref("SpiceJet_Booking_Details")} AS l
