
config {
  type: "table",
  tags: ["satellite"],
  schema: "Row_Vault",
  partitionBy: "load_dts",
  clusterBy: ["PassengerID_bk"]
}
 
SELECT
  TO_HEX(SHA256(CAST(PassengerID AS STRING))) AS PassengerID_hk,
  PassengerID AS PassengerID_bk,
  FirstName,LastName,DOB,Email,CreatedDateTime,LastupdateDateTime,
  CURRENT_DATE() AS load_dts,
  'Airindia_AI_Passenger_Details' AS record_source
FROM
  ${ref("Airindia_AI_Passenger_Details")}
