
config {
  type: "table",
  tags: ["satellite"],
  schema: "Row_Vault",
  partitionBy: "load_dts",
  clusterBy: ["FlightID_bk"]
}
 
SELECT
  TO_HEX(SHA256(CAST(FlightID AS STRING))) AS FlightID_hk,
  FlightID AS FlightID_bk,
  FlightNumber,ArrivalDateTime,ScheduledDepartureDateTime,ActualDepartureDateTime,OriginAirportCode,DestinationAirportCode,SeatCapacity,AvailableSeats,
  CURRENT_DATE() AS load_dts,
  'Airindia_Flight_Details' AS record_source
FROM
  ${ref("Airindia_Flight_Details")}
